# Generated by Django 4.0.5 on 2022-06-29 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familiares', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiar',
            name='apellido',
        ),
    ]
